[LGTM] Fix error cpp/potentially-dangerous-function (#40)
* [LGTM] Fix error cpp/potentially-dangerous-function

Use of a standard library function that is not thread-safe.

https://lgtm.com/rules/2154840805/

Query pack: com.lgtm/cpp-queries
Query ID: cpp/potentially-dangerous-function
Language: C/C++
Severity: Warning
Tags: reliability security external/cwe/cwe-676

The time related functions such as `gmtime` fill data into a `tm` struct or char array in shared memory and then returns a pointer to that memory. If the function is called from multiple places in the same program, and especially if it is called from multiple threads in the same program, then the calls will overwrite each other's data.

* Use local buffers for reading asctime / localtime values.

* Need #define special case for compiling on Windows

```
D:\a\1\s\libsrc\File.cc(78): error C3861: 'localtime_r': identifier not found [D:\a\1\a\mylib.vcxproj]
D:\a\1\s\libsrc\File.cc(78): error C3861: 'asctime_r': identifier not found [D:\a\1\a\mylib.vcxproj]
```